version: '3.7'

services:

  gateway:
    container_name: cfp-gateway
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf

  # frontend:
  #   container_name: cfp-frontend
  #   image: node
  #   restart: always
  #   ports:
  #     - 4000:4000

  # backend:
  #   container_name: cfp-backend
  #   image: node
  #   restart: always
  #   ports:
  #     - 3000:3000

  mariadb:
    container_name: cfp-mariadb
    image: mariadb
    restart: always
    command: --lower_case_table_names=1
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ./data:/var/lib/mysql

  redis:
    container_name: cfp-redis
    image: redis
    restart: always
    ports:
      - 6379:6379
