version: '3.7'

services:

  gateway:
    container_name: cfp-gateway
    image: nginx
    restart: always
    # ports:
    #   - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    network_mode: host
    # networks:
    #   cfp_net:
    #     ipv4_address: 172.16.18.100

  frontend:
    container_name: cfp-frontend
    build: 
      context: './conf/frontend'
      dockerfile: Dockerfile
    restart: always
    # ports:
    #   - 8080:8080
    network_mode: host
    # networks:
    #   cfp_net:
    #     ipv4_address: 172.16.18.101

  backend:
    env_file: './conf/backend/.env'
    container_name: cfp-backend
    build: 
      context: './conf/backend'
      dockerfile: Dockerfile
    restart: always
    # ports:
    #   - 3000:3000
    network_mode: host
    # networks:
    #   cfp_net:
    #     ipv4_address: 172.16.18.102

  mariadb:
    container_name: cfp-mariadb
    image: mariadb
    restart: always
    command: --lower_case_table_names=1
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    # ports:
    #   - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ./data:/var/lib/mysql
      # - ./conf/mysql/my.cnf:/etc/mysql/conf.d/mysql_local.cnf:ro
    network_mode: host
    # networks:
    #   cfp_net:
    #     ipv4_address: 172.16.18.103

  redis:
    container_name: cfp-redis
    image: redis
    restart: always
    # ports:
    #   - 6379:6379
    network_mode: host
    # networks:
    #   cfp_net:
    #     ipv4_address: 172.16.18.104

# networks:
#   cfp_net:
#     external: true